### ISSUE TITLE
Handling unavailable IPFS data

### ISSUE THREAD

**Issue by Airtune** [BananoCoin/banano-metanode-nft#10]
Should an NFT be strictly unavailable for nodes that can't access (unpinned) IPFS data?

Should an NFT be invalidated if it doesn't point to a data point in IPFS?

Since the checksum in the ledger is collision resistant meta nodes could bootstrap the JSON from each other trustlessly so as long as 1 node has the JSON it can spread to the other nodes.

**Comment by coranos** [comment]
Since NFTs are art and the art is stored in IPFS, I would think a network outage that prevents access to IPFS would be really bad.

We shouldn't try to reimplement IPFS. If anything, nodes should ask each-other which templates they have via the get_nft_template_list api call, and queue new templates with a call to get_nft_template_owner (which caches the template).
